doctrine:
    dbal:
        default_connection: local
        connections:
            local:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL_LOCAL)%'
            remote:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL_REMOTE)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: local
        entity_managers:
            auto_mapping: true
            local:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                connection: local
                mappings:
                    Local:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Local'
                        prefix: 'App\Entity\Local'
                        alias: Local
            remote:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: remote
                mappings:
                    Remote:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Remote'
                        prefix: 'App\Entity\Remote'
                        alias: Remote
