version: '3.6'

services:
    app:
        image: app
        build:
            context: .
            target: web-dev
            args:
                SYMFONY_VERSION: ${SYMFONY_VERSION:-}
                STABILITY: ${STABILITY:-stable}
        ports:
            - 8080:80
        volumes:
            - $PWD:/var/www/html

    mariadb:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password

